### ISSUE TITLE
18.2-7 answer isn't seems like what is expected from the question

### ISSUE THREAD

**Issue by Amila-Rukshan** [walkccc/CLRS#107]
Given answer have not considered the milli or nano prefix in the unit though! 

I think it asks approximately minimize the B-tree search time. We can interpret the a+bt time equation as follows. a is a constant time independent of read or write of a page, it may be moving the head from one track to another. bt is the expected time spent in reading or writing t items of the page. When a = bt, we have at least spent a time equal to the amount we waste as a. Therefore t = b/a = (5ms)/(10us) = 500 ( page size)

I think this is what they expect from the question.

**Comment by th0114nd** [comment]
The logic is correct in 18.2-7, but the input is off by an order of magnitude. In the solution, `a` and `b` are treated as having the same units, and so instead should arrive at `0 = t(ln t - 1) - 500` instead of `0 = t (ln t - 1) - 0.5`. That gives t = 129, which passes the sanity check of 50 <= t <= 2000

**Comment by walkccc** [comment]
I'm going to close this. Feel free to reopen it.
