### ISSUE TITLE
Exercise 12.3-5 running time is not O(h)

### ISSUE THREAD

**Issue by ywxkQQc** [walkccc/CLRS#320]
The worst-case running time of `TREE-PREDECESSOR`  is O(lg(n) * lg(n)) since the 7th line could be executed O(lg(n)) times and the running time of `PARENT` is O(lg(n)). 

I rewrite the `TREE-PREDECESSOR` .

```
TREE-PREDECESSOR(T, x)
    if x.left != NIL
        return TREE-MAXIMUM(x.left)
    y = T.root
    pred = NIL
    while y != NIL and y.key != x.key
        if y.key < x.key
            pred = y
            y = y.left
        else y = y.right
    return pred
```

**Comment by walkccc** [comment]
Thanks for pointing out this issue.
Yes, we should avoid calling `PARENT` in `TREE-PREDECESSOR` and we should aim for a O(lg n) algorithm to find the predecessor since we're given a BST.

It seems that your pseudocode is not correct. I've updated the solution [here](https://walkccc.github.io/CLRS/Chap12/12.3/#123-5) and provided examples in the [.cpp code](https://github.com/walkccc/CLRS-cpp/blob/master/Chap12/12.3-5/12.3-5.cpp#L42).

Hope this helps. Thanks.
