### ISSUE TITLE
Problem with Exercise 5.2-2

### ISSUE THREAD

**Issue by kaizokun** [walkccc/CLRS#4]
I was looking for the answer of the exercice 5.2-2 and I'm asking myself if is is correct. Because there are cases that are not take into account I think, but I'm not sure.

For example if we hire first the candidate with the rank k (for example: k = 3) and directly after, we hire the candidate with the rank n (ex: 6) the procedure hire exactly twice too. But the solution doesn't take these events into account.

**Comment by walkccc** [comment]
I think the solution is already take these cases into account.

Here I replace your k with i for clear explanation with the solution.

The first candidate hired must have index = 1, and here you say that it's rank is i (where i = 3). If we directly hire the candidate with index = 2 and its rank is n (where n is the highest), this is one of the condition that 

Let E_i be the event in which candidate 1 has rank i (where i = 3).

Since n = 6, the candidates with 3 < rank < 6 (i.e., rank = 4 & 5) must be interviewed after candidates 6. And the probability is 1 / 3.

S[All events of the order of rank 4, rank 5 and rank 6] = {645, 654, 465, 456, 546, 564}

P[rank 4 and rank 5 are both after rank 6] = 2 / 6.

Is this clear for you?

**Comment by kaizokun** [comment]
thanks for your answer I'll study it as soon I have time.

**Comment by kaizokun** [comment]
After review, the solution is actually right, it is just another way to see things. I tried a solution more combinatory but far less efficient even if I get the same result

   @Test
    public void hireTwiceTestMethod1() {

        double total = 0;
        //for each rank for the candidate 1 [ 1, n [
        for (int i = 1; i <= n - 1; i++) {
            //for each number of candidates with a rank < i, checked before the candidate with rank n 
            for (int b = 0; b <= i - 1; b++) {
               //here we have a number of arrangements  of b candidates with rank < i 
               //multiplied by the number of candidate left after the one with rank n
               //so after the rank n is hired you can have candidates with rank < i
                total += (factorial(i - 1) / factorial(i - 1 - b)) * factorial(n - b - 2);
            }
        } 

        double rs = total / factorial(n);

        System.out.println(rs);
    }

the result is the same than with this procedure from the official solution manual

   @Test
    public void hireTwiceTestMethod2() {

        double rs = nThHarmonicNumber(n - 1) / n;

        System.out.println(rs);
    }

    public static double factorial(double n) {

        if (n <= 1) {
            return 1;
        }

        return n * factorial(n - 1);
    }

    public static double nThHarmonicNumber(double n){

        double total = 0;

        while( n >= 1 ){

            total += 1.0 / n;

            n --;
        }

        return total;
    }
